using DifferentialCalculus.Interfaces;
using DifferentialCalculus.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DifferentialCalculus.Repositories
{
    public class ProblemRepository : IProblemRepository
    {
        private Dictionary<string, List<string>> _bookSections = new Dictionary<string, List<string>>();
        private Dictionary<string, List<Problem>> _differentialCalculus = new Dictionary<string, List<Problem>>();
        private Dictionary<string, Dictionary<string, List<Problem>>> _books = new Dictionary<string, Dictionary<string, List<Problem>>>();

        public ProblemRepository()
        {
            _bookSections.Add(Books.DifferentialCalculus, new List<string>
                {
                    "1.R",
                    "1.1",
                    "1.2",
                    "1.3",
                    "1.4",
                    "1.5",
                    "1.6",
                    "1.7",
                    "2.R",
                    "2.1",
                    "2.2",
                    "2.3",
                    "2.4",
                    "2.5",
                    "2.6",
                    "2.7",
                    "2.8",
                    "3.R",
                    "3.1",
                    "3.2",
                    "3.3",
                    "3.4",
                    "3.5",
                    "3.6",
                    "3.7",
                    "3.8",
                    "3.9",
                    "4.R",
                    "4.1",
                    "4.2",
                    "4.3",
                    "4.4",
                    "4.5",
                    "4.6",
                    "4.7",
                    "4.8",
                    "5.R",
                    "5.1",
                    "5.2",
                    "5.3",
                    "5.4",
                    "5.5",
                    "5.6",
                    "5.7",
                    "5.8",
                    "5.9",
                    "6.R",
                    "6.1",
                    "6.2",
                    "6.3",
                    "6.4",
                    "6.5",
                    "6.6",
                    "6.7",
                    "6.8",
                    "7.R",
                    "7.1",
                    "7.2",
                    "7.3",
                    "7.4",
                    "7.5",
                    "7.6",
                    "8.R",
                    "8.1",
                    "8.2",
                    "8.3",
                    "8.4",
                    "8.5",
                    "8.6",
                    "8.7",
                    "8.8",
                    "9.R",
                    "9.1",
                    "9.2",
                    "9.3",
                    "9.4",
                    "9.5",
                    "9.6",
                    "9.7",
                    "10.R",
                    "10.1",
                    "10.2",
                    "10.3",
                    "10.4",
                    "10.5",
                    "11.R",
                    "11.1",
                    "11.2",
                    "11.3",
                    "11.4",
                    "11.5",
                    "11.6",
                    "11.7",
                    "11.8",
                    "12.R",
                    "12.1",
                    "12.2",
                    "12.3",
                    "12.4",
                    "12.5",
                    "12.6",
                    "12.7",
                    "12.8",
                    "12.9",
                    "13.R",
                    "13.1",
                    "13.2",
                    "13.3",
                    "13.4",
                    "13.5",
                    "13.6",
                    "13.7",
                    "13.8",
                });

            _books.Add(Books.DifferentialCalculus, _differentialCalculus);
            // Chapter 1
            _differentialCalculus.Add("1.R", new List<Problem> 
            {
                new Problem { Number = 1, Images = new List<string> { "content/IMG_20200404_144745976.jpg" } },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 }
            });
            _differentialCalculus.Add("1.1", new List<Problem>
            {
                new Problem { Number = 1, Images = new List<string> { "content/chapter1/1.1/1.1-1.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 2, Images = new List<string> { "content/chapter1/1.1/1.1-2.jpg" }, Answer = "" },
                new Problem { Number = 3, Images = new List<string> { "content/chapter1/1.1/1.1-3.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 4, Images = new List<string> { "content/chapter1/1.1/1.1-4.jpg" }, Answer = "" },
                new Problem { Number = 5, Images = new List<string> { "content/chapter1/1.1/1.1-5.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 6, Images = new List<string> { "content/chapter1/1.1/1.1-6.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 7, Images = new List<string> { "content/chapter1/1.1/1.1-7.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 8, Images = new List<string> { "content/chapter1/1.1/1.1-8.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 9, Images = new List<string> { "content/chapter1/1.1/1.1-9.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 10, Images = new List<string> { "content/chapter1/1.1/1.1-10.jpg" }, Answer = "" },
                new Problem { Number = 11, Images = new List<string> { "content/chapter1/1.1/1.1-11.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 12, Images = new List<string> { "content/chapter1/1.1/1.1-12.jpg" }, Answer = "", VerifiedCorrect = true },
                new Problem { Number = 13, Images = new List<string> { "content/chapter1/1.1/1.1-13.jpg" }, Answer = "" },
                new Problem { Number = 14, Images = new List<string> { "content/chapter1/1.1/1.1-14.jpg" }, Answer = "" },
                new Problem { Number = 15, Images = new List<string> { "content/chapter1/1.1/1.1-15.jpg" }, Answer = "" },
                new Problem { Number = 16, Images = new List<string> { "content/chapter1/1.1/1.1-16.jpg" }, Answer = "" },
                new Problem { Number = 17, Images = new List<string> { "content/chapter1/1.1/1.1-17.jpg" }, Answer = "" },
                new Problem { Number = 18, Images = new List<string> { "content/chapter1/1.1/1.1-18.jpg" }, Answer = "" },
                new Problem { Number = 19, Images = new List<string> { "content/chapter1/1.1/1.1-19.jpg" }, Answer = "" },
                new Problem { Number = 20, Images = new List<string> { "content/chapter1/1.1/1.1-20.jpg" }, Answer = "" },
                new Problem { Number = 21, Images = new List<string> { "content/chapter1/1.1/1.1-21.jpg" }, Answer = "" },
                new Problem { Number = 22, Images = new List<string> { "content/chapter1/1.1/1.1-22.jpg" }, Answer = "" },
                new Problem { Number = 23, Images = new List<string> { "content/chapter1/1.1/1.1-23a.jpg", "content/chapter1/1.1/1.1-23b.jpg" }, Answer = "" },
                new Problem { Number = 24, Images = new List<string> { "content/chapter1/1.1/1.1-24.jpg" }, Answer = "" },
                new Problem { Number = 25, Images = new List<string> { "content/chapter1/1.1/1.1-25.jpg" }, Answer = "" },
                new Problem { Number = 26, Images = new List<string> { "content/chapter1/1.1/1.1-26.jpg" }, Answer = "" },
                new Problem { Number = 27, Images = new List<string> { "content/chapter1/1.1/1.1-27.jpg" }, Answer = "" },
                new Problem { Number = 28, Images = new List<string> { "content/chapter1/1.1/1.1-28.jpg" }, Answer = "" },
                new Problem { Number = 29, Images = new List<string> { "content/chapter1/1.1/1.1-29.jpg" }, Answer = "" },
                new Problem { Number = 30, Images = new List<string> { "content/chapter1/1.1/1.1-30.jpg" }, Answer = "" },
                new Problem { Number = 31, Images = new List<string> { "content/chapter1/1.1/1.1-31.jpg" }, Answer = "" },
                new Problem { Number = 32, Images = new List<string> { "content/chapter1/1.1/1.1-32.jpg" }, Answer = "" },
                new Problem { Number = 33, Images = new List<string> { "content/chapter1/1.1/1.1-33.jpg" }, Answer = "" },
                new Problem { Number = 34, Images = new List<string> { "content/chapter1/1.1/1.1-34.jpg" }, Answer = "" },
                new Problem { Number = 35, Images = new List<string> { "content/chapter1/1.1/1.1-35.jpg" }, Answer = "" },
                new Problem { Number = 36, Images = new List<string> { "content/chapter1/1.1/1.1-36.jpg" }, Answer = "" },
                new Problem { Number = 37, Images = new List<string> { "content/chapter1/1.1/1.1-37.jpg" }, Answer = "" },
                new Problem { Number = 38, Images = new List<string> { "content/chapter1/1.1/1.1-38.jpg" }, Answer = "" },
                new Problem { Number = 39, Images = new List<string> { "content/chapter1/1.1/1.1-39.jpg" }, Answer = "" },
                new Problem { Number = 40, Images = new List<string> { "content/chapter1/1.1/1.1-40.jpg" }, Answer = "" },
                new Problem { Number = 41, Images = new List<string> { "content/chapter1/1.1/1.1-41.jpg" }, Answer = "" },
                new Problem { Number = 42, Images = new List<string> { "content/chapter1/1.1/1.1-42.jpg" }, Answer = "" },
                new Problem { Number = 43, Images = new List<string> { "content/chapter1/1.1/1.1-43.jpg" }, Answer = "" },
                new Problem { Number = 44, Images = new List<string> { "content/chapter1/1.1/1.1-44.jpg" }, Answer = "" },
                new Problem { Number = 45, Images = new List<string> { "content/chapter1/1.1/1.1-45.jpg" }, Answer = "" },
                new Problem { Number = 46, Images = new List<string> { "content/chapter1/1.1/1.1-46.jpg" }, Answer = "" },
                new Problem { Number = 47, Images = new List<string> { "content/chapter1/1.1/1.1-47.jpg" }, Answer = "" },
                new Problem { Number = 48, Images = new List<string> { "content/chapter1/1.1/1.1-48.jpg" }, Answer = "" },
                new Problem { Number = 49, Images = new List<string> { "content/chapter1/1.1/1.1-49.jpg" }, Answer = "" },
                new Problem { Number = 50, Images = new List<string> { "content/chapter1/1.1/1.1-50.jpg" }, Answer = "" },
                new Problem { Number = 51, Images = new List<string> { "content/chapter1/1.1/1.1-51.jpg" }, Answer = "" },
                new Problem { Number = 52, Images = new List<string> { "content/chapter1/1.1/1.1-52.jpg" }, Answer = "" },
                new Problem { Number = 53, Images = new List<string> { "content/chapter1/1.1/1.1-53.jpg" }, Answer = "" },
                new Problem { Number = 54, Images = new List<string> { "content/chapter1/1.1/1.1-54.jpg" }, Answer = "" },
                new Problem { Number = 55, Images = new List<string> { "content/chapter1/1.1/1.1-55.jpg" }, Answer = "" },
                new Problem { Number = 56, Images = new List<string> { "content/chapter1/1.1/1.1-56.jpg" }, Answer = "" },
                new Problem { Number = 57, Images = new List<string> { "content/chapter1/1.1/1.1-57.jpg" }, Answer = "" },
                new Problem { Number = 58, Images = new List<string> { "content/chapter1/1.1/1.1-58.jpg" }, Answer = "" },
                new Problem { Number = 59, Images = new List<string> { "content/chapter1/1.1/1.1-59.jpg" }, Answer = "" },
                new Problem { Number = 60, Images = new List<string> { "content/chapter1/1.1/1.1-60.jpg" }, Answer = "" },
                new Problem { Number = 61, Images = new List<string> { "content/chapter1/1.1/1.1-61.jpg" }, Answer = "" },
                new Problem { Number = 62, Images = new List<string> { "content/chapter1/1.1/1.1-62.jpg" }, Answer = "" },
                new Problem { Number = 63, Images = new List<string> { "content/chapter1/1.1/1.1-63.jpg" }, Answer = "" },
                new Problem { Number = 64, Images = new List<string> { "content/chapter1/1.1/1.1-64.jpg" }, Answer = "" },
                new Problem { Number = 65, Images = new List<string> { "content/chapter1/1.1/1.1-65.jpg" }, Answer = "" },
                new Problem { Number = 66, Images = new List<string> { "content/chapter1/1.1/1.1-66.jpg" }, Answer = "" },
                new Problem { Number = 67, Images = new List<string> { "content/chapter1/1.1/1.1-67.jpg" }, Answer = "" },
                new Problem { Number = 68, Images = new List<string> { "content/chapter1/1.1/1.1-68.jpg" }, Answer = "" },
                new Problem { Number = 69, Images = new List<string> { "content/chapter1/1.1/1.1-69.jpg" }, Answer = "" },
                new Problem { Number = 70, Images = new List<string> { "content/chapter1/1.1/1.1-70.jpg" }, Answer = "" },
                new Problem { Number = 71, Images = new List<string> { "content/chapter1/1.1/1.1-71.jpg" }, Answer = "" },
                new Problem { Number = 72, Images = new List<string> { "content/chapter1/1.1/1.1-72.jpg" }, Answer = "" },
                new Problem { Number = 73, Images = new List<string> { "content/chapter1/1.1/1.1-73.jpg" }, Answer = "" },
                new Problem { Number = 74, Images = new List<string> { "content/chapter1/1.1/1.1-74.jpg" }, Answer = "" }
            });
            _differentialCalculus.Add("1.2", new List<Problem> 
            {
                new Problem { Number = 1, Images = new List<string> { "content/chapter1/1.2/1.2-1.jpg" }, Answer = "" },
                new Problem { Number = 2, Images = new List<string> { "content/chapter1/1.2/1.2-2.jpg" }, Answer = "" },
                new Problem { Number = 3, Images = new List<string> { "content/chapter1/1.2/1.2-3.jpg" }, Answer = "" },
                new Problem { Number = 4, Images = new List<string> { "content/chapter1/1.2/1.2-4a.jpg", "content/chapter1/1.2/1.2-4b.jpg" }, Answer = "" },
                new Problem { Number = 5, Images = new List<string> { "content/chapter1/1.2/1.2-5.jpg" }, Answer = "" },
                new Problem { Number = 6, Images = new List<string> { "content/chapter1/1.2/1.2-6.jpg" }, Answer = "" },
                new Problem { Number = 7, Images = new List<string> { "content/chapter1/1.2/1.2-7.jpg" }, Answer = "" },
                new Problem { Number = 8, Images = new List<string> { "content/chapter1/1.2/1.2-8.jpg" }, Answer = "" },
                new Problem { Number = 9, Images = new List<string> { "content/chapter1/1.2/1.2-9.jpg" }, Answer = "" },
                new Problem { Number = 10, Images = new List<string> { "content/chapter1/1.2/1.2-10.jpg" }, Answer = "" },
                new Problem { Number = 11, Images = new List<string> { "content/chapter1/1.2/1.2-11.jpg" }, Answer = "" },
                new Problem { Number = 12, Images = new List<string> { "content/chapter1/1.2/1.2-12.jpg" }, Answer = "" },
                new Problem { Number = 13, Images = new List<string> { "content/chapter1/1.2/1.2-13.jpg" }, Answer = "" },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 }
            });
            _differentialCalculus.Add("1.3", new List<Problem>
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 },
                new Problem { Number = 56 },
                new Problem { Number = 57 },
                new Problem { Number = 58 },
                new Problem { Number = 59 },
                new Problem { Number = 60 },
                new Problem { Number = 61 },
                new Problem { Number = 62 },
                new Problem { Number = 63 },
                new Problem { Number = 64 }
            });
            _differentialCalculus.Add("1.4", new List<Problem>
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 }
            });
            _differentialCalculus.Add("1.5", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 }
            });
            _differentialCalculus.Add("1.6", new List<Problem>
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 },
                new Problem { Number = 56 },
                new Problem { Number = 57 },
                new Problem { Number = 58 },
                new Problem { Number = 59 },
                new Problem { Number = 60 },
                new Problem { Number = 61 },
                new Problem { Number = 62 }
            });
            _differentialCalculus.Add("1.7", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 }
            });

            // Chapter 2
            _differentialCalculus.Add("2.R", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 }
            });
            _differentialCalculus.Add("2.1", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 }
            });
            _differentialCalculus.Add("2.2", new List<Problem>
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 }
            });
            _differentialCalculus.Add("2.3", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 }
            });
            _differentialCalculus.Add("2.4", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 }
            });
            _differentialCalculus.Add("2.5", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 },
                new Problem { Number = 56 },
                new Problem { Number = 57 },
                new Problem { Number = 58 }
            });
            _differentialCalculus.Add("2.6", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 }
            });
            _differentialCalculus.Add("2.7", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 }
            });
            _differentialCalculus.Add("2.8", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 }
            });

            // Chapter 3
            _differentialCalculus.Add("3.R", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 },
                new Problem { Number = 56 },
                new Problem { Number = 57 },
                new Problem { Number = 58 },
                new Problem { Number = 59 },
                new Problem { Number = 60 },
                new Problem { Number = 61 },
                new Problem { Number = 62 },
                new Problem { Number = 63 },
                new Problem { Number = 64 },
                new Problem { Number = 65 },
                new Problem { Number = 66 },
                new Problem { Number = 67 },
                new Problem { Number = 68 },
                new Problem { Number = 69 },
                new Problem { Number = 70 },
                new Problem { Number = 71 },
                new Problem { Number = 72 },
                new Problem { Number = 73 },
                new Problem { Number = 74 },
                new Problem { Number = 75 },
                new Problem { Number = 76 },
                new Problem { Number = 77 },
                new Problem { Number = 78 },
                new Problem { Number = 79 },
                new Problem { Number = 80 }
            });
            _differentialCalculus.Add("3.1", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 },
                new Problem { Number = 56 },
                new Problem { Number = 57 },
                new Problem { Number = 58 },
                new Problem { Number = 59 },
                new Problem { Number = 60 },
                new Problem { Number = 61 },
                new Problem { Number = 62 },
                new Problem { Number = 63 },
                new Problem { Number = 64 },
                new Problem { Number = 65 },
                new Problem { Number = 66 },
                new Problem { Number = 67 },
                new Problem { Number = 68 },
                new Problem { Number = 69 },
                new Problem { Number = 70 },
                new Problem { Number = 71 },
                new Problem { Number = 72 },
                new Problem { Number = 73 },
                new Problem { Number = 74 }
            });
            _differentialCalculus.Add("3.2", new List<Problem> 
            {
                new Problem { Number = 1 },
                new Problem { Number = 2 },
                new Problem { Number = 3 },
                new Problem { Number = 4 },
                new Problem { Number = 5 },
                new Problem { Number = 6 },
                new Problem { Number = 7 },
                new Problem { Number = 8 },
                new Problem { Number = 9 },
                new Problem { Number = 10 },
                new Problem { Number = 11 },
                new Problem { Number = 12 },
                new Problem { Number = 13 },
                new Problem { Number = 14 },
                new Problem { Number = 15 },
                new Problem { Number = 16 },
                new Problem { Number = 17 },
                new Problem { Number = 18 },
                new Problem { Number = 19 },
                new Problem { Number = 20 },
                new Problem { Number = 21 },
                new Problem { Number = 22 },
                new Problem { Number = 23 },
                new Problem { Number = 24 },
                new Problem { Number = 25 },
                new Problem { Number = 26 },
                new Problem { Number = 27 },
                new Problem { Number = 28 },
                new Problem { Number = 29 },
                new Problem { Number = 30 },
                new Problem { Number = 31 },
                new Problem { Number = 32 },
                new Problem { Number = 33 },
                new Problem { Number = 34 },
                new Problem { Number = 35 },
                new Problem { Number = 36 },
                new Problem { Number = 37 },
                new Problem { Number = 38 },
                new Problem { Number = 39 },
                new Problem { Number = 40 },
                new Problem { Number = 41 },
                new Problem { Number = 42 },
                new Problem { Number = 43 },
                new Problem { Number = 44 },
                new Problem { Number = 45 },
                new Problem { Number = 46 },
                new Problem { Number = 47 },
                new Problem { Number = 48 },
                new Problem { Number = 49 },
                new Problem { Number = 50 },
                new Problem { Number = 51 },
                new Problem { Number = 52 },
                new Problem { Number = 53 },
                new Problem { Number = 54 },
                new Problem { Number = 55 },
                new Problem { Number = 56 },
                new Problem { Number = 57 },
                new Problem { Number = 58 },
                new Problem { Number = 59 },
                new Problem { Number = 60 }
            });
        }

        public List<string> GetSectionTitles(string book)
        {
            return _bookSections[book];
        }

        public List<Problem> GetProblems(string book, string sectionTitle)
        {
            try
            {
                return _books[book][sectionTitle];
            }
            catch(Exception)
            {
                Problem example = new Problem { Number = 0, Answer = "<h1>Select a Section and Problem from the top left menu.</br> This site contains all the answers to:</br>ISBN: 0495557420</br>ISBN-13: 9780495557425</br>Authors:James Stewart</br></h1>", Images = new List<string> { "content/9688171_1375654336_Width288.jpg" } };
                List<Problem> problems = new List<Problem>();
                problems.Add(example);
                return problems;
            }
        }
    }
}
